# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\LFT.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LFTWidget(object):
    def setupUi(self, LFTWidget):
        LFTWidget.setObjectName("LFTWidget")
        LFTWidget.resize(600, 300)
        self.gridLayout = QtWidgets.QGridLayout(LFTWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(LFTWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Client = QtWidgets.QWidget()
        self.tab_Client.setObjectName("tab_Client")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_Client)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_IP_Send = QtWidgets.QLabel(self.tab_Client)
        self.label_IP_Send.setObjectName("label_IP_Send")
        self.horizontalLayout_2.addWidget(self.label_IP_Send)
        self.lE_IP_Send = QtWidgets.QLineEdit(self.tab_Client)
        self.lE_IP_Send.setObjectName("lE_IP_Send")
        self.horizontalLayout_2.addWidget(self.lE_IP_Send)
        self.label_Port_Send = QtWidgets.QLabel(self.tab_Client)
        self.label_Port_Send.setObjectName("label_Port_Send")
        self.horizontalLayout_2.addWidget(self.label_Port_Send)
        self.lE_Port_Send = QtWidgets.QLineEdit(self.tab_Client)
        self.lE_Port_Send.setObjectName("lE_Port_Send")
        self.horizontalLayout_2.addWidget(self.lE_Port_Send)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.lV_Send = QtWidgets.QListView(self.tab_Client)
        self.lV_Send.setObjectName("lV_Send")
        self.gridLayout_2.addWidget(self.lV_Send, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pB_Add = QtWidgets.QPushButton(self.tab_Client)
        self.pB_Add.setObjectName("pB_Add")
        self.verticalLayout.addWidget(self.pB_Add)
        self.pB_Delete = QtWidgets.QPushButton(self.tab_Client)
        self.pB_Delete.setObjectName("pB_Delete")
        self.verticalLayout.addWidget(self.pB_Delete)
        self.pB_Browse_File = QtWidgets.QPushButton(self.tab_Client)
        self.pB_Browse_File.setObjectName("pB_Browse_File")
        self.verticalLayout.addWidget(self.pB_Browse_File)
        self.pB_Browse_Dir = QtWidgets.QPushButton(self.tab_Client)
        self.pB_Browse_Dir.setObjectName("pB_Browse_Dir")
        self.verticalLayout.addWidget(self.pB_Browse_Dir)
        self.pB_Clear_Send = QtWidgets.QPushButton(self.tab_Client)
        self.pB_Clear_Send.setObjectName("pB_Clear_Send")
        self.verticalLayout.addWidget(self.pB_Clear_Send)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pB_Send = QtWidgets.QPushButton(self.tab_Client)
        self.pB_Send.setObjectName("pB_Send")
        self.verticalLayout.addWidget(self.pB_Send)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_Client, "")
        self.tab_Scan = QtWidgets.QWidget()
        self.tab_Scan.setObjectName("tab_Scan")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_Scan)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_IP_Scan = QtWidgets.QLabel(self.tab_Scan)
        self.label_IP_Scan.setObjectName("label_IP_Scan")
        self.horizontalLayout.addWidget(self.label_IP_Scan)
        self.lE_IP_Scan = QtWidgets.QLineEdit(self.tab_Scan)
        self.lE_IP_Scan.setObjectName("lE_IP_Scan")
        self.horizontalLayout.addWidget(self.lE_IP_Scan)
        self.label_Port_Scan = QtWidgets.QLabel(self.tab_Scan)
        self.label_Port_Scan.setObjectName("label_Port_Scan")
        self.horizontalLayout.addWidget(self.label_Port_Scan)
        self.lE_Port_Scan = QtWidgets.QLineEdit(self.tab_Scan)
        self.lE_Port_Scan.setObjectName("lE_Port_Scan")
        self.horizontalLayout.addWidget(self.lE_Port_Scan)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.lV_Scan = QtWidgets.QListView(self.tab_Scan)
        self.lV_Scan.setObjectName("lV_Scan")
        self.gridLayout_3.addWidget(self.lV_Scan, 1, 0, 2, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pB_Clear_Scan = QtWidgets.QPushButton(self.tab_Scan)
        self.pB_Clear_Scan.setObjectName("pB_Clear_Scan")
        self.verticalLayout_2.addWidget(self.pB_Clear_Scan)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.pB_Scan = QtWidgets.QPushButton(self.tab_Scan)
        self.pB_Scan.setObjectName("pB_Scan")
        self.verticalLayout_2.addWidget(self.pB_Scan)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_Scan, "")
        self.tab_Server = QtWidgets.QWidget()
        self.tab_Server.setObjectName("tab_Server")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_Server)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lV_Server = QtWidgets.QListView(self.tab_Server)
        self.lV_Server.setObjectName("lV_Server")
        self.gridLayout_4.addWidget(self.lV_Server, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pB_Clear_Server = QtWidgets.QPushButton(self.tab_Server)
        self.pB_Clear_Server.setObjectName("pB_Clear_Server")
        self.verticalLayout_3.addWidget(self.pB_Clear_Server)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.pB_Start = QtWidgets.QPushButton(self.tab_Server)
        self.pB_Start.setObjectName("pB_Start")
        self.verticalLayout_3.addWidget(self.pB_Start)
        self.pB_End = QtWidgets.QPushButton(self.tab_Server)
        self.pB_End.setObjectName("pB_End")
        self.verticalLayout_3.addWidget(self.pB_End)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_Server, "")
        self.tab_Setting = QtWidgets.QWidget()
        self.tab_Setting.setObjectName("tab_Setting")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_Setting)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_Server = QtWidgets.QLabel(self.tab_Setting)
        self.label_Server.setObjectName("label_Server")
        self.gridLayout_7.addWidget(self.label_Server, 0, 0, 1, 1)
        self.label_Client = QtWidgets.QLabel(self.tab_Setting)
        self.label_Client.setObjectName("label_Client")
        self.gridLayout_7.addWidget(self.label_Client, 2, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_Client_port = QtWidgets.QLabel(self.tab_Setting)
        self.label_Client_port.setObjectName("label_Client_port")
        self.gridLayout_6.addWidget(self.label_Client_port, 0, 0, 1, 1)
        self.lE_Client_port = QtWidgets.QLineEdit(self.tab_Setting)
        self.lE_Client_port.setObjectName("lE_Client_port")
        self.gridLayout_6.addWidget(self.lE_Client_port, 0, 1, 1, 1)
        self.label_Client_IP = QtWidgets.QLabel(self.tab_Setting)
        self.label_Client_IP.setObjectName("label_Client_IP")
        self.gridLayout_6.addWidget(self.label_Client_IP, 1, 0, 1, 1)
        self.lE_Client_IP = QtWidgets.QLineEdit(self.tab_Setting)
        self.lE_Client_IP.setObjectName("lE_Client_IP")
        self.gridLayout_6.addWidget(self.lE_Client_IP, 1, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 3, 0, 1, 1)
        self.pB_Apply = QtWidgets.QPushButton(self.tab_Setting)
        self.pB_Apply.setObjectName("pB_Apply")
        self.gridLayout_7.addWidget(self.pB_Apply, 4, 1, 1, 1)
        self.pB_Reset = QtWidgets.QPushButton(self.tab_Setting)
        self.pB_Reset.setObjectName("pB_Reset")
        self.gridLayout_7.addWidget(self.pB_Reset, 4, 2, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lE_Server_save_path = QtWidgets.QLineEdit(self.tab_Setting)
        self.lE_Server_save_path.setObjectName("lE_Server_save_path")
        self.gridLayout_5.addWidget(self.lE_Server_save_path, 3, 1, 1, 1)
        self.label_Server_save_path = QtWidgets.QLabel(self.tab_Setting)
        self.label_Server_save_path.setObjectName("label_Server_save_path")
        self.gridLayout_5.addWidget(self.label_Server_save_path, 3, 0, 1, 1)
        self.label_Server_IP = QtWidgets.QLabel(self.tab_Setting)
        self.label_Server_IP.setObjectName("label_Server_IP")
        self.gridLayout_5.addWidget(self.label_Server_IP, 2, 0, 1, 1)
        self.label_Server_name = QtWidgets.QLabel(self.tab_Setting)
        self.label_Server_name.setObjectName("label_Server_name")
        self.gridLayout_5.addWidget(self.label_Server_name, 0, 0, 1, 1)
        self.lE_Server_IP = QtWidgets.QLineEdit(self.tab_Setting)
        self.lE_Server_IP.setObjectName("lE_Server_IP")
        self.gridLayout_5.addWidget(self.lE_Server_IP, 2, 1, 1, 1)
        self.label_Server_port = QtWidgets.QLabel(self.tab_Setting)
        self.label_Server_port.setObjectName("label_Server_port")
        self.gridLayout_5.addWidget(self.label_Server_port, 1, 0, 1, 1)
        self.lE_Server_name = QtWidgets.QLineEdit(self.tab_Setting)
        self.lE_Server_name.setObjectName("lE_Server_name")
        self.gridLayout_5.addWidget(self.lE_Server_name, 0, 1, 1, 1)
        self.lE_Server_port = QtWidgets.QLineEdit(self.tab_Setting)
        self.lE_Server_port.setObjectName("lE_Server_port")
        self.gridLayout_5.addWidget(self.lE_Server_port, 1, 1, 1, 1)
        self.pB_Browse_save_path = QtWidgets.QPushButton(self.tab_Setting)
        self.pB_Browse_save_path.setObjectName("pB_Browse_save_path")
        self.gridLayout_5.addWidget(self.pB_Browse_save_path, 3, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab_Setting, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.label_IP_Send.setBuddy(self.lE_IP_Scan)
        self.label_Port_Send.setBuddy(self.lE_Port_Scan)
        self.label_IP_Scan.setBuddy(self.lE_IP_Scan)
        self.label_Port_Scan.setBuddy(self.lE_Port_Scan)
        self.label_Client_port.setBuddy(self.lE_Client_port)
        self.label_Client_IP.setBuddy(self.lE_Client_IP)
        self.label_Server_save_path.setBuddy(self.lE_Server_save_path)
        self.label_Server_IP.setBuddy(self.lE_Server_IP)
        self.label_Server_name.setBuddy(self.lE_Server_name)
        self.label_Server_port.setBuddy(self.lE_Server_port)

        self.retranslateUi(LFTWidget)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(LFTWidget)
        LFTWidget.setTabOrder(self.tabWidget, self.pB_Send)
        LFTWidget.setTabOrder(self.pB_Send, self.pB_Add)
        LFTWidget.setTabOrder(self.pB_Add, self.pB_Delete)
        LFTWidget.setTabOrder(self.pB_Delete, self.pB_Browse_File)
        LFTWidget.setTabOrder(self.pB_Browse_File, self.pB_Clear_Send)
        LFTWidget.setTabOrder(self.pB_Clear_Send, self.lV_Send)
        LFTWidget.setTabOrder(self.lV_Send, self.lE_IP_Scan)
        LFTWidget.setTabOrder(self.lE_IP_Scan, self.lE_Port_Scan)
        LFTWidget.setTabOrder(self.lE_Port_Scan, self.pB_Scan)
        LFTWidget.setTabOrder(self.pB_Scan, self.pB_Clear_Scan)
        LFTWidget.setTabOrder(self.pB_Clear_Scan, self.lV_Scan)
        LFTWidget.setTabOrder(self.lV_Scan, self.pB_Start)
        LFTWidget.setTabOrder(self.pB_Start, self.pB_End)
        LFTWidget.setTabOrder(self.pB_End, self.pB_Clear_Server)

    def retranslateUi(self, LFTWidget):
        _translate = QtCore.QCoreApplication.translate
        LFTWidget.setWindowTitle(_translate("LFTWidget", "LFT"))
        self.label_IP_Send.setText(_translate("LFTWidget", "IP"))
        self.label_Port_Send.setText(_translate("LFTWidget", "Port"))
        self.pB_Add.setText(_translate("LFTWidget", "Add"))
        self.pB_Delete.setText(_translate("LFTWidget", "Delete"))
        self.pB_Browse_File.setText(_translate("LFTWidget", "Browse File"))
        self.pB_Browse_Dir.setText(_translate("LFTWidget", "Browse Dir"))
        self.pB_Clear_Send.setText(_translate("LFTWidget", "Clear"))
        self.pB_Send.setText(_translate("LFTWidget", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Client), _translate("LFTWidget", "Send"))
        self.label_IP_Scan.setText(_translate("LFTWidget", "IP"))
        self.label_Port_Scan.setText(_translate("LFTWidget", "Port"))
        self.pB_Clear_Scan.setText(_translate("LFTWidget", "Clear"))
        self.pB_Scan.setText(_translate("LFTWidget", "Scan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Scan), _translate("LFTWidget", "Scan"))
        self.pB_Clear_Server.setText(_translate("LFTWidget", "Clear"))
        self.pB_Start.setText(_translate("LFTWidget", "Start"))
        self.pB_End.setText(_translate("LFTWidget", "End"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Server), _translate("LFTWidget", "Server"))
        self.label_Server.setText(_translate("LFTWidget", "Server:"))
        self.label_Client.setText(_translate("LFTWidget", "Client"))
        self.label_Client_port.setText(_translate("LFTWidget", "port"))
        self.label_Client_IP.setText(_translate("LFTWidget", "server IP"))
        self.pB_Apply.setText(_translate("LFTWidget", "Apply"))
        self.pB_Reset.setText(_translate("LFTWidget", "Reset"))
        self.label_Server_save_path.setText(_translate("LFTWidget", "save path"))
        self.label_Server_IP.setText(_translate("LFTWidget", "listen IP"))
        self.label_Server_name.setText(_translate("LFTWidget", "name"))
        self.label_Server_port.setText(_translate("LFTWidget", "port"))
        self.pB_Browse_save_path.setText(_translate("LFTWidget", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Setting), _translate("LFTWidget", "Setting"))
